routes/web.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KategoriSiswaController;
use App\Http\Controllers\Landing\HalamanKelasController;
use App\Http\Controllers\Landing\ProfileController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
Route::get('/edit', [ProfileController::class, 'edit'])->name('edit.profile');
Route::put('/update', [ProfileController::class, 'update'])->name('update.profile');
Route::get('/header', [ProfileController::class, 'header'])->name('header');
Route::get('/cetak/{raporId}', [ProfileController::class, 'cetak'])->name('print');
Route::get('/cetak-siswa', [ProfileController::class, 'cetakSiswa'])->name('siswa-print');
// Authentication
Route::get('login', [AuthController::class, 'login'])->name('login');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'registerUser'])->name('registerUser');
Route::post('login', [AuthController::class, 'authenticate']);
Route::post('logout', [AuthController::class, 'logout'])->name('logout');

// Route::middleware(['auth'], function(){
    Route::post('/reset-password', [ProfileController::class, 'resetPassword'])->name('reset-password');
    // });
    // route::get('kelas', [HalamanKelasController::class, 'getKelas'])->name('kelas');
    
    Route::group(['prefix' => 'kelas', 'middleware' => ['auth']], function () {
        Route::get('/', [HalamanKelasController::class, 'index'])->name('list.kelas');
        Route::get('/{kelasId}', [HalamanKelasController::class, 'show'])->name('detail.kelas');
        Route::put('/{kelasId}', [HalamanKelasController::class, 'changeStatus'])->name('changeStatus');
});

Route::group(['prefix' => 'exam', 'middleware' => ['auth']], function(){
    Route::get('/', [HalamanQuizController::class, 'index'])->name('list.exam');
    Route::get('/{examId}', [HalamanQuizController::class, 'show'])->name('detail.exam');
    Route::post('/{examId}', [HalamanQuizController::class, 'test'])->name('test');
});
Route::group([
    'middleware' => ['auth']
], function () {
    Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Admin,Mentor']], function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::resource('role', RoleController::class);
        Route::resource('user', UserController::class);
        Route::get('/user/{id}/{status}', [UserController::class, 'changeStatus'])->name('change-status');
        Route::post('/user/{id}/reset', [UserController::class, 'reset'])->name('reset');
        Route::resource('kategori-siswa', KategoriSiswaController::class);
        Route::resource('siswa', SiswaController::class);
        Route::resource('mentor', MentorController::class);
        Route::resource('class', KelasController::class);
        Route::get('/class/{kelasId}/assign', [KelasController::class, 'assign_kelas'])->name('assign_kelas');
        Route::post('/class/{kelasId}/assign', [KelasController::class, 'assign'])->name('assign');
        Route::resource('rapor', RaporController::class);
        Route::get('/cetak/{id}', [RaporController::class, 'cetak'])->name('cetak');
        
        Route::group(['prefix' => 'quiz'], function(){
            
            Route::resource('quiz-image', QuizImageController::class);
            Route::resource('quiz-sound', QuizSoundController::class);
            Route::resource('quiz-text', QuizTextController::class);
            Route::resource('quiz-video', QuizVideoController::class);
            
            Route::resource('question', QuestionController::class);
            Route::resource('exam', ExamController::class);
            Route::get('/exam/{examId}/assign', [ExamController::class, 'assign_exam'])->name('assign.exam');
            Route::post('/exam/{examId}/student', [ExamController::class, 'student'])->name('store_assign');
        });
    });
});
Route::get('/{path}', [HelperController::class, 'image'])->name('files.image');
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('files');

app/Models/Exam.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Exam extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
     
    protected $fillable = [
        'name',
        'image',
        'status'
    ];

    public function exam_question(){
        return $this->hasMany(ExamQuestion::class, 'exam_id', 'id');
    }
    public function test_result(){
        return $this->hasMany(TestResult::class,'exam_id', 'id');
    }

    public function exam_students(){
        return $this->hasMany(ExamStudent::class, 'exam_id', 'id');
    }
}

app/Models/Quiz.php
<?php

namespace App\Models;

use App\Http\Controllers\Question;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Quiz extends Model
{
    use HasFactory;
    protected $guarded = [
        'id'
    ];
    protected $table = 'quiz';

    public function questions(){
        return $this->hasMany(Question::class, 'quiz_id', 'id');
    }
}

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use App\Models\Exam;
use App\Models\ExamQuestion;
use App\Models\ExamStudent;
use App\Models\ExamUser;
use App\Models\Mentor;
use App\Models\Question;
use App\Models\Siswa;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ExamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user()->id;
        if(Auth::user()->role_id == 3){
            $exam = Exam::where('name', 'LIKE', '%' . $request->keyword . '%')->where('created_by', $user)->paginate(5);
    
            return view('pages.dashboard.quiz.exam.index', compact('exam'));
        }
        $exam = Exam::where('name', 'LIKE', '%' . $request->keyword . '%')->paginate(5);
    
        return view('pages.dashboard.quiz.exam.index', compact('exam'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user()->id;
        $question = Question::where('created_by', $user)->get();
        return view('pages.dashboard.quiz.exam.create', compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required|string',
            'image' => 'required|image|mimes:png,jpg,jpeg'
        ]);

        DB::beginTransaction();
        try {

            $image  = $request->file('image');
            $image->storeAs('exam-image', $image->hashName());
            $exam = new Exam();
            $exam->name = $request->title;
            $exam->image = $image->hashName();
            $exam->created_by = Auth::id();
            $exam->save();

            if ((is_array($request->questions))) {
                foreach ($request->questions as $key => $examQuestion) {

                    // $examArray = array(
                    $eQuestion = new ExamQuestion();
                    $eQuestion->exam_id = $exam->id;
                    $eQuestion->question_id  = $examQuestion;
                    // );
                    $eQuestion->save();
                }
            }
            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            return $e;
        }
        return redirect()->route('exam.index')->with(['success' => 'Data berhasil disimpan!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $exam = Exam::find($id);
        $question = Question::with('question_options')->whereHas('exam_question', function ($q) use ($exam) {
            $q->where('exam_id', $exam->id);
        })->with([
            'question_options', 'quiz_texts', 'quiz_images', 'quiz_videos', 'quiz_sounds'
        ])->paginate(1);
        return view('pages.dashboard.quiz.exam.show', compact(['exam', 'question']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $exam = Exam::with('exam_question.question.question_options')->find($id);
        $questions = Question::all();
        return view('pages.dashboard.quiz.exam.edit', compact(['exam', 'questions']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $exam = Exam::find($id);

        DB::beginTransaction();
        try {
            $exam->name = $request->title;
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $image->storeAs('exam-image', $image->hashName());
                $exam->image = $image->hashName();
            }
            $exam->created_by = Auth::id();
            $exam->save();

            if (is_array($request->questions)) {
                $exam->exam_question()->delete();
                foreach ($request->questions as $key => $examQuestion) {
                    $eQuestion = new ExamQuestion();
                    $eQuestion->exam_id = $exam->id;
                    $eQuestion->question_id = $examQuestion;
                    $eQuestion->save();
                }
            }
            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            return $e;
        }
        return redirect()->route('exam.index')->with(['success' => 'Data berhasil disimpan!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $exam = Exam::findOrFail($id);
        $exam->exam_question()->delete();
        $exam->delete();
        return redirect()->route('exam.index')->with(['success' => 'Data berhasil dihapus!']);
    }
    
    public function assign_exam($examId){
        $exam = Exam::findOrFail($examId);
        $user_id = $exam->created_by;
        $mentor = Mentor::where('user_id', $user_id)->first();
        $siswa = Siswa::where('mentor_id', $mentor->id)->whereHas('exam_students', function($q) use ($exam) {
            $q->where('exam_id', $exam->id);
            $q->where('siswa_id', '<>', 'siswa.id');
        })->get();
        $siswa = Siswa::where('mentor_id', $mentor->id)->whereNotIn('id', $siswa->modelKeys())->whereHas('user', function($query){
            $query->where('status', 'Active');
        })->get();
        return view ('pages.dashboard.quiz.exam.assign', compact(['exam', 'siswa']));
    }
    
    public function student (Request $request, $examId){
        $this->validate($request, [
            'siswa_ids' => 'required',
            'siswa_ids.*'
        ]);
        $exam = Exam::findOrFail($examId);
        DB::beginTransaction();
        try{
            if((is_array($request->siswa_ids))){
                foreach($request->siswa_ids as $key => $siswaIds){
                    ExamStudent::create([
                        'exam_id' => $exam->id,
                        'siswa_id' => $siswaIds
                    ]);
                }
            }else{
            echo "error";
            }
            DB::commit();
            return redirect()->route('exam.index')->with(['success' => 'Data berhasil disimpan!']);
        }catch(Exception $e){
            DB::rollBack();
            return $e;
        }
    }
}

app/Http/Controllers/QuizController.php
<?php

namespace App\Http\Controllers;

use App\Models\Quiz;
use Illuminate\Http\Request;

class QuizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $quiz = Quiz::paginate();
        return view('pages.dashboard.quiz.subject.index', compact('quiz'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required'
        ]);

        $quiz = Quiz::create([
            'title' => $request->title
        ]);

        if ($quiz) {
            return redirect()->route('subject-quiz.index')->with(['success' => 'Data berhasil disimpan!']);
        } else {
            return redirect()->route('subject-quiz.index')->with(['error' => 'Data gagal disimpan!']);
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $quiz = Quiz::all();

        return view('pages.dashboard.quiz.subject.index',compact($quiz));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $quiz = Quiz::find($id);
        $quiz->title = $request->title;
        $quiz->save();
        if ($quiz) {
            return redirect()->route('subject-quiz.index')->with(['success' => 'Data berhasil diedit!']);
        } else {
            return redirect()->route('subject-quiz.index')->with(['error' => 'Data gagal diedit!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $quiz = Quiz::find($id);

        $quiz->delete();

        return redirect()->route('subject-quiz.index')->with(['success' => 'Data berhasil dihapus!']);
    }
}

resources/views/pages/dashboard/quiz/exam/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambah Question')

@section('content')
<div class="flex justify-between mt-10">
    <span class="self-center text-gray-600">
     Tambah Data Exam | <a href="{{URL::previous()}}">Data Exam </a> <span class="font-semibold"> - Tambah Exam</span>
 </span> 
 <div class="col-span-3 mt-2 md:col-span-2">
     <a href="{{ route('exam.index') }}"
         class="w-full px-3 py-2 border rounded-md shadow-sm text-dark bg-slate-50 focus:outline-none hover:bg-slate-100"><i class="pr-3 fa-solid fa-arrow-left"></i>Kembali</a>
 </div>
 </div>
    <div class="p-5 mt-5 mb-20 bg-white rounded shadow-sm">
        <form action="{{ route('exam.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="mt-5">
                <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Title</label>
                <input type="text" name="title" value="{{ old('title') }}"
                    class="w-full p-2 mt-2 border border-gray-200 rounded shadow-sm bg-slate-50 focus:outline-none focus:bg-white"
                    placeholder="Cth: Soal Bahasa Inggris" required>
                @error('name')
                    <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="mt-5">
                <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase" for="image">
                    Image</label>
                <input
                    class="block w-full mb-5 text-xs text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-zinc-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                    id="image" type="file" name="image">
            </div>
            <div class="field_wrapper">
                <div class="relative">
                  <div class="flex gap-x-6">
                    <select name="questions[]" id="" class="block w-full px-4 py-3 pr-8 mb-3 leading-tight text-gray-700 border border-gray-200 rounded appearance-none bg-slate-50 focus:outline-none focus:bg-white focus:border-gray-500">
                        <option value="">Select An Option</option>
                       @foreach ($question as $item)
                       <option value="{{$item->id}}">{{$item->name}}</option>
                       @endforeach 
                    </select>
                      <a href="javascript:void(0);" class="px-6 mt-2 add_button " title="Add field"><img src="{{ asset('/assets/img/plus-circle.svg') }}"></a>
                  </div>
                </div>
            </div>
            
            <div class="mt-5">
                <button type="submit"
                    class="p-2 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">SIMPAN
                    EXAM</button>
            </div>

        </form>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            var maxField = 10; //Input fields increment limitation
            var addButton = $('.add_button'); //Add button selector
            var wrapper = $('.field_wrapper'); //Input field wrapper
            var fieldHTML = '<div class= "flex gap-x-6"><select name="questions[]" id="" class="block w-full px-4 py-3 pr-8 mb-3 leading-tight text-gray-700 border border-gray-200 rounded appearance-none bg-slate-50 focus:outline-none focus:bg-white focus:border-gray-500"><option value="">Select An Option</option>@foreach($question as $item)<option value="{{$item->id}}">{{$item->name}}</option>@endforeach </select><a href="javascript:void(0);" class="px-6 mt-2 remove_button"><img src={{asset('assets/img/minus-circle.svg')}}></a></div>'; //New input field html 
            var x = 1; //Initial field counter is 1
            
            //Once add button is clicked
            $(addButton).click(function(){
                //Check maximum number of input fields
                if(x < maxField){ 
                    x++; //Increment field counter
                    $(wrapper).append(fieldHTML); //Add field html
                }
            });
            
            //Once remove button is clicked
            $(wrapper).on('click', '.remove_button', function(e){
                e.preventDefault();
                $(this).parent('div').remove(); //Remove field html
                x--; //Decrement field counter
            });
        });
        </script>
@endsection

     

resources/views/pages/dashboard/quiz/exam/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambah Question')

@section('content')
<div class="flex justify-between mt-10">
    <span class="self-center text-gray-600">
     Edit Data Exam | <a href="{{URL::previous()}}">Data Exam </a> <span class="font-semibold"> - Edit Exam</span>
 </span> 
 <div class="col-span-3 mt-2 md:col-span-2">
     <a href="{{ route('exam.index') }}"
         class="w-full px-3 py-2 border rounded-md shadow-sm text-dark bg-slate-50 focus:outline-none hover:bg-slate-100"><i class="pr-3 fa-solid fa-arrow-left"></i>Kembali</a>
 </div>
 </div>
    <div class="p-5 mt-5 mb-20 bg-white rounded shadow-sm">
        <form action="{{ route('exam.update', $exam->id) }}" method="POST" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="mt-5">
                <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Title</label>
                <input type="text" name="title" value="{{ old('title', $exam->name) }}"
                    class="w-full p-2 mt-2 border border-gray-200 rounded shadow-sm bg-slate-50 focus:outline-none focus:bg-white"
                    placeholder="Cth: Soal Bahasa Inggris" required>
                @error('name')
                    <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="mt-5">
                <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase" for="image">
                    Image</label>
                <input
                    class="block w-full mb-5 text-xs text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-zinc-50 "
                    id="image" type="file" name="image">
                    @if ($exam->image)
                    <img class="py-5 w-[400px] h-[400px]" src="{{asset('storage/exam-image/' . $exam->image)}}">
                @endif
            </div>
            <div class="field_wrapper">
                <div class="relative">
                    @foreach($exam->exam_question as $item)
                    <div class="flex gap-x-6">
                        <select name="questions[]" id="" class="block w-full px-4 py-3 pr-8 mb-3 leading-tight text-gray-700 border border-gray-200 rounded appearance-none bg-slate-50 focus:outline-none focus:bg-white focus:border-gray-500">
                        {{-- {{$item}} --}}
                        {{-- <option value="">Select An Option</option> --}}
                        @foreach($questions as $question)
                       {{-- <option value="{{$question->id}}">{{old($item->question->id) == $question->id ? 'selected' : ''}} {{$question->name}}</option> --}}
                       <option value="{{$item->question->id}}" {{$item->question->id == $question->id ? 'selected' : ''}}>{{old($item->question->name,$question->name)}}</option>
                       @endforeach
                    </select>
                </div>
                @endforeach
                </div>
            </div>
            
            <div class="mt-5">
                <button type="submit"
                    class="p-2 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">SIMPAN
                    EXAM</button>
            </div>

        </form>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
@endsection

     

resources/views/pages/dashboard/quiz/exam/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Image')

@section('content')
    <div class="p-5 mt-20 bg-white rounded shadow-sm">
        <div class="flex justify-between py-2 mb-3">
            <div >
                <p class="text-base font-semibold ">
                    Data Quiz
                </p>
                <p class="text-sm text-slate-500">Daftar quiz <span class="text-primary"> Naladhipa Courses</span></p>
            </div>
            @if (Auth::user()->role_id == 3)    
            <div class="col-span-3 mt-2 md:col-span-2">
                <a href="{{ route('exam.create') }}"
                    class="w-full p-3 text-white uppercase bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">TAMBAH
                    quiz</a>
            </div>
            @endif
        </div>
        <div class="grid grid-cols-6 mb-4 md:grid-cols-8 md:gap-4 ">
            <div class="col-span-3 md:col-span-3">
                <form action="{{ route('exam.index') }}" method="GET">
                    <input type="text" name="keyword"
                        class="w-full p-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                        placeholder="Search...">
                </form>
            </div>
        </div>

        <div class="md:relative sm:rounded-lg">
            <div class="flex items-center justify-between pb-4">

            </div>
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr class="items-center">
                        <th scope="col" class="px-6 py-3 ">
                            No
                        </th>
                        <th scope="col" class="px-6 py-3 ">
                            Title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Aksi
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($exam as $key => $item)
                        <tr class="bg-white border-b hover:bg-gray-50 ">
                            <td class="px-6 py-4">
                                <div class="pl-3">
                                    <p class="text-base font-semibold">{{ $key + 1 }}</p>
                                </div>
                            </td>
                            <td class="px-6 py-4">
                                <p class="text-base font-medium">{{ $item->name }}</p>
                            </td>
                            <td class="inline-flex items-center self-center px-6 py-4 ">
                                @if (Auth::user()->role_id == 1)
                                <a href="{{route('assign.exam', $item->id)}}" type="button" class="self-center text-white bg-gray-400 hover:bg-gray-600 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center">Tambah Siswa</a>
                                @endif
                                @if (Auth::user()->role_id == 3)      
                                <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown-{{ $item }}"
                                    class="self-center text-white bg-gray-400 hover:bg-gray-600 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center"
                                    type="button">Aksi <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none"
                                        stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M19 9l-7 7-7-7"></path>
                                    </svg></button>
                                @endif
                                <!-- Dropdown menu -->
                             
                                <div id="dropdown-{{ $item }}"
                                    class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                                    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200"
                                        aria-labelledby="dropdownDefaultButton">
                                        <li>
                                            <a href="{{ route('exam.edit', $item->id) }}"
                                                class="block px-4 py-2 ">Edit</a>
                                        </li>
                                        @if (Auth::user()->role_id == 1)     
                                        <li>
                                            <a href="{{ route('assign.exam', $item->id) }}"
                                                class="block px-4 py-2 ">Assign</a>
                                        </li>
                                        @endif
                                        <li>
                                            <a href="{{ route('exam.show', $item->id) }}"
                                                class="block px-4 py-2 ">Detail</a>
                                        </li>
                                        <li>
                                            <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                                action="{{ route('exam.destroy', $item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit"
                                                    class="w-full px-4 py-2 text-left hover:bg-gray-100 focus:outline-none">
                                                    Delete</button>
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <div class="p-3 mb-3 text-white bg-red-500 rounded shadow-sm">
                            Data Belum Tersedia!
                        </div>
                    @endforelse

                </tbody>
            </table>
            <div class="mt-2">
                {{ $exam->links('vendor.pagination.tailwind') }}
            </div>
        </div>
    </div>


@endsection