routes/web.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KategoriSiswaController;
use App\Http\Controllers\Landing\HalamanKelasController;
use App\Http\Controllers\Landing\ProfileController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
Route::get('/edit', [ProfileController::class, 'edit'])->name('edit.profile');
Route::put('/update', [ProfileController::class, 'update'])->name('update.profile');
Route::get('/header', [ProfileController::class, 'header'])->name('header');
Route::get('/cetak/{raporId}', [ProfileController::class, 'cetak'])->name('print');
Route::get('/cetak-siswa', [ProfileController::class, 'cetakSiswa'])->name('siswa-print');
// Authentication
Route::get('login', [AuthController::class, 'login'])->name('login');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'registerUser'])->name('registerUser');
Route::post('login', [AuthController::class, 'authenticate']);
Route::post('logout', [AuthController::class, 'logout'])->name('logout');

// Route::middleware(['auth'], function(){
    Route::post('/reset-password', [ProfileController::class, 'resetPassword'])->name('reset-password');
    // });
    // route::get('kelas', [HalamanKelasController::class, 'getKelas'])->name('kelas');
    
    Route::group(['prefix' => 'kelas', 'middleware' => ['auth']], function () {
        Route::get('/', [HalamanKelasController::class, 'index'])->name('list.kelas');
        Route::get('/{kelasId}', [HalamanKelasController::class, 'show'])->name('detail.kelas');
        Route::put('/{kelasId}', [HalamanKelasController::class, 'changeStatus'])->name('changeStatus');
});

Route::group(['prefix' => 'exam', 'middleware' => ['auth']], function(){
    Route::get('/', [HalamanQuizController::class, 'index'])->name('list.exam');
    Route::get('/{examId}', [HalamanQuizController::class, 'show'])->name('detail.exam');
    Route::post('/{examId}', [HalamanQuizController::class, 'test'])->name('test');
});
Route::group([
    'middleware' => ['auth']
], function () {
    Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Admin,Mentor']], function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::resource('role', RoleController::class);
        Route::resource('user', UserController::class);
        Route::get('/user/{id}/{status}', [UserController::class, 'changeStatus'])->name('change-status');
        Route::post('/user/{id}/reset', [UserController::class, 'reset'])->name('reset');
        Route::resource('kategori-siswa', KategoriSiswaController::class);
        Route::resource('siswa', SiswaController::class);
        Route::resource('mentor', MentorController::class);
        Route::resource('class', KelasController::class);
        Route::get('/class/{kelasId}/assign', [KelasController::class, 'assign_kelas'])->name('assign_kelas');
        Route::post('/class/{kelasId}/assign', [KelasController::class, 'assign'])->name('assign');
        Route::resource('rapor', RaporController::class);
        Route::get('/cetak/{id}', [RaporController::class, 'cetak'])->name('cetak');
        
        Route::group(['prefix' => 'quiz'], function(){
            
            Route::resource('quiz-image', QuizImageController::class);
            Route::resource('quiz-sound', QuizSoundController::class);
            Route::resource('quiz-text', QuizTextController::class);
            Route::resource('quiz-video', QuizVideoController::class);
            
            Route::resource('question', QuestionController::class);
            Route::resource('exam', ExamController::class);
            Route::get('/exam/{examId}/assign', [ExamController::class, 'assign_exam'])->name('assign.exam');
            Route::post('/exam/{examId}/student', [ExamController::class, 'student'])->name('store_assign');
        });
    });
});
Route::get('/{path}', [HelperController::class, 'image'])->name('files.image');
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('files');

app/Models/Quiz.php
<?php

namespace App\Models;

use App\Http\Controllers\Question;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Quiz extends Model
{
    use HasFactory;
    protected $guarded = [
        'id'
    ];
    protected $table = 'quiz';

    public function questions(){
        return $this->hasMany(Question::class, 'quiz_id', 'id');
    }
}

app/Http/Controllers/QuizController.php
<?php

namespace App\Http\Controllers;

use App\Models\Quiz;
use Illuminate\Http\Request;

class QuizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $quiz = Quiz::paginate();
        return view('pages.dashboard.quiz.subject.index', compact('quiz'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required'
        ]);

        $quiz = Quiz::create([
            'title' => $request->title
        ]);

        if ($quiz) {
            return redirect()->route('subject-quiz.index')->with(['success' => 'Data berhasil disimpan!']);
        } else {
            return redirect()->route('subject-quiz.index')->with(['error' => 'Data gagal disimpan!']);
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $quiz = Quiz::all();

        return view('pages.dashboard.quiz.subject.index',compact($quiz));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $quiz = Quiz::find($id);
        $quiz->title = $request->title;
        $quiz->save();
        if ($quiz) {
            return redirect()->route('subject-quiz.index')->with(['success' => 'Data berhasil diedit!']);
        } else {
            return redirect()->route('subject-quiz.index')->with(['error' => 'Data gagal diedit!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $quiz = Quiz::find($id);

        $quiz->delete();

        return redirect()->route('subject-quiz.index')->with(['success' => 'Data berhasil dihapus!']);
    }
}

resources/views/pages/dashboard/quiz/video/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Edit Quiz Image')

@section('content')
<div class="flex justify-between mt-20">
    <span class="self-center text-gray-600">
     Edit Data  | <a href="{{ route('quiz-video.index') }}">Master Data  </a> <span class="font-semibold"> - Edit Data</span>
 </span> 
 <div class="col-span-3 mt-2 md:col-span-2">
     <a href="{{ route('quiz-video.index') }}"
         class="w-full px-3 py-2 border rounded-md shadow-sm text-dark bg-slate-50 focus:outline-none hover:bg-slate-100"><i class="pr-3 fa-solid fa-arrow-left"></i>Kembali</a>
 </div>
 </div>
    <div class="min-h-screen pb-10 mt-10">
        <div class="p-5 bg-white rounded shadow-sm ">
            <form action="{{ route('quiz-video.update', $video->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Judul
                        Pertanyaan</label>
                    <input type="text" name="title" value="{{ old('title', $video->title) }}"
                        class="w-full p-2 mt-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                        placeholder="Cth: Soal gambar" required>
                    @error('title')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Video
                        Pertanyaan</label>
                    <div class="flex">
                        <span class="inline-flex items-center p-2 px-3 text-sm text-gray-900 bg-gray-100 border border-r-0 border-gray-300 rounded-l-md ">
                            Youtube.com/
                          </span>
                          <input type="text" name="video" value="{{ old('video', $video->video) }}"
                              class="w-full p-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                              placeholder="....." required>
                    </div>
                    @error('title')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
            
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Caption
                        Soal</label>
                    <textarea id="message" rows="4" name='caption' value="{{ old('caption', $video->caption) }}"
                        class="block p-2.5 w-full text-sm focus:border-gray-500 text-gray-900 bg-zinc-50 rounded-lg border border-gray-300"
                        placeholder="Deskripsi soal ..." required>{{ old('caption', $video->caption) }}</textarea>
                    @error('caption')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mt-5">
                    <button type="submit"
                        class="p-2 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">SIMPAN
                        QUIZ</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/dashboard/quiz/video/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Image')

@section('content')
    <div class="p-5 mt-20 bg-white rounded shadow-sm">
        <div class="flex justify-between py-2 mb-3">
            <div >
                <p class="text-base font-semibold ">
                    Master Data
                </p>
                <p class="text-sm text-slate-500"> <span class="text-primary"> Naladhipa Courses</span></p>
            </div>
            <div class="col-span-3 mt-2 md:col-span-2">
                <a href="javascript;"
                    class="w-full p-3 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700 modal-open ">Tambah
                    Data</a>
            </div>
        </div>
        <div class="grid grid-cols-6 mb-4 md:grid-cols-8 md:gap-4 ">
            <div class="col-span-3 md:col-span-3">
                <form action="{{ route('quiz-video.index') }}" method="GET">
                    <input type="text" name="keyword"
                        class="w-full p-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                        placeholder="Search...">
                </form>
            </div>
        </div>

        <div class="md:relative sm:rounded-lg">
            <div class="flex items-center justify-between pb-4">

            </div>
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr class="items-center">
                        <th scope="col" class="px-6 py-3 ">
                            No
                        </th>
                        <th scope="col" class="px-6 py-3 ">
                            Title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Aksi
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($video as $key => $item)
                        <tr class="bg-white border-b hover:bg-gray-50 ">
                            <td class="px-6 py-4">
                                <div class="pl-3">
                                    <p class="text-base font-semibold">{{ $key + 1 }}</p>
                                </div>
                            </td>
                            <td class="px-6 py-4">
                                <p class="text-base font-medium">{{ $item->title }}</p>
                            </td>
                            <td class="inline-flex items-center self-center px-6 py-4 ">
                                <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown-{{ $item }}"
                                    class="self-center text-white bg-gray-400 hover:bg-gray-600 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center"
                                    type="button">Aksi <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none"
                                        stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M19 9l-7 7-7-7"></path>
                                    </svg></button>
                                <!-- Dropdown menu -->
                                <div id="dropdown-{{ $item }}"
                                    class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                                    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200"
                                        aria-labelledby="dropdownDefaultButton">
                                        <li>
                                            <a href="{{ route('quiz-video.edit', $item->id) }}"
                                                class="block px-4 py-2 ">Edit</a>
                                        </li>
                                        <li>
                                            <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                                action="{{ route('quiz-video.destroy', $item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit"
                                                    class="w-full px-4 py-2 text-left hover:bg-gray-100 focus:outline-none">
                                                    Delete</button>
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <div class="p-3 mb-3 text-white bg-red-500 rounded shadow-sm">
                            Data Belum Tersedia!
                        </div>
                    @endforelse

                </tbody>
            </table>
            <div class="mt-2">
                {{ $video->withQueryString()->links('vendor.pagination.tailwind') }}
            </div>
        </div>
    </div>


    <!--Modal-->
    <div class="fixed top-0 left-0 flex items-center justify-center w-full h-full opacity-0 pointer-events-none modal">
        <div class="absolute w-full h-full bg-gray-900 opacity-50 modal-overlay"></div>

        <div class="z-50 w-11/12 mx-auto overflow-y-auto bg-white rounded shadow-lg modal-container md:max-w-md">

            <!-- Add margin if you want to see some of the overlay behind the modal-->
            <div class="px-6 py-4 text-left modal-content">
                <!--Title-->
                <div class="flex items-center justify-between pb-3">
                    <p class="text-2xl font-bold">Tambah Data</p>
                    <div class="z-50 cursor-pointer modal-close">
                        <svg class="text-black fill-current" xmlns="http://www.w3.org/2000/svg" width="18"
                            height="18" viewBox="0 0 18 18">
                            <path
                                d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z">
                            </path>
                        </svg>
                    </div>
                </div>
                <form action="{{ route('quiz-video.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <!--Body-->
                    <div class="mt-5">
                        <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Judul
                            Pertanyaan</label>
                        <input type="text" name="title" value="{{ old('title') }}"
                            class="w-full p-2 mt-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                            placeholder="Cth: Soal gambar" required>
                        @error('title')
                            <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="mt-5">
                        <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Video
                            Pertanyaan</label>
                        <div class="flex">
                            <span class="inline-flex items-center p-2 px-3 text-sm text-gray-900 bg-gray-100 border border-r-0 border-gray-300 rounded-l-md ">
                                Youtube.com/
                              </span>
                              <input type="text" name="video" value="{{ old('video') }}"
                                  class="w-full p-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                                  placeholder="....." required>
                        </div>
                        @error('title')
                            <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="mt-5">
                        <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Caption
                            Soal</label>
                        <textarea id="message" rows="4" name='caption' value="{{ old('caption') }}"
                            class="block p-2.5 w-full text-sm focus:border-gray-500 text-gray-900 bg-zinc-50 rounded-lg border border-gray-300"
                            placeholder="Deskripsi kelas ..." required>{{ old('caption') }}</textarea>
                        @error('caption')
                            <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>

                    <!--Footer-->
                    <div class="flex justify-end pt-2">
                        <button type="submit"
                            class="p-3 px-4 mr-2 text-white bg-indigo-500 rounded-lg hover:bg-indigo-700">Simpan</button>
                    </div>
                </form>

            </div>
        </div>
    </div>


    <script>
        var openmodal = document.querySelectorAll('.modal-open')
        for (var i = 0; i < openmodal.length; i++) {
            openmodal[i].addEventListener('click', function(event) {
                event.preventDefault()
                toggleModal()
            })
        }

        const overlay = document.querySelector('.modal-overlay')
        overlay.addEventListener('click', toggleModal)

        var closemodal = document.querySelectorAll('.modal-close')
        for (var i = 0; i < closemodal.length; i++) {
            closemodal[i].addEventListener('click', toggleModal)
        }

        document.onkeydown = function(evt) {
            evt = evt || window.event
            var isEscape = false
            if ("key" in evt) {
                isEscape = (evt.key === "Escape" || evt.key === "Esc")
            } else {
                isEscape = (evt.keyCode === 27)
            }
            if (isEscape && document.body.classList.contains('modal-active')) {
                toggleModal()
            }
        };


        function toggleModal() {
            const body = document.querySelector('body')
            const modal = document.querySelector('.modal')
            modal.classList.toggle('opacity-0')
            modal.classList.toggle('pointer-events-none')
            body.classList.toggle('modal-active')
        }
    </script>



    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/datepicker.min.js"></script>
@endsection