routes/web.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KategoriSiswaController;
use App\Http\Controllers\Landing\HalamanKelasController;
use App\Http\Controllers\Landing\ProfileController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
Route::get('/edit', [ProfileController::class, 'edit'])->name('edit.profile');
Route::put('/update', [ProfileController::class, 'update'])->name('update.profile');
Route::get('/header', [ProfileController::class, 'header'])->name('header');
Route::get('/cetak/{raporId}', [ProfileController::class, 'cetak'])->name('print');
Route::get('/cetak-siswa', [ProfileController::class, 'cetakSiswa'])->name('siswa-print');
// Authentication
Route::get('login', [AuthController::class, 'login'])->name('login');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'registerUser'])->name('registerUser');
Route::post('login', [AuthController::class, 'authenticate']);
Route::post('logout', [AuthController::class, 'logout'])->name('logout');

// Route::middleware(['auth'], function(){
    Route::post('/reset-password', [ProfileController::class, 'resetPassword'])->name('reset-password');
    // });
    // route::get('kelas', [HalamanKelasController::class, 'getKelas'])->name('kelas');
    
    Route::group(['prefix' => 'kelas', 'middleware' => ['auth']], function () {
        Route::get('/', [HalamanKelasController::class, 'index'])->name('list.kelas');
        Route::get('/{kelasId}', [HalamanKelasController::class, 'show'])->name('detail.kelas');
        Route::put('/{kelasId}', [HalamanKelasController::class, 'changeStatus'])->name('changeStatus');
});

Route::group(['prefix' => 'exam', 'middleware' => ['auth']], function(){
    Route::get('/', [HalamanQuizController::class, 'index'])->name('list.exam');
    Route::get('/{examId}', [HalamanQuizController::class, 'show'])->name('detail.exam');
    Route::post('/{examId}', [HalamanQuizController::class, 'test'])->name('test');
});
Route::group([
    'middleware' => ['auth']
], function () {
    Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Admin,Mentor']], function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::resource('role', RoleController::class);
        Route::resource('user', UserController::class);
        Route::get('/user/{id}/{status}', [UserController::class, 'changeStatus'])->name('change-status');
        Route::post('/user/{id}/reset', [UserController::class, 'reset'])->name('reset');
        Route::resource('kategori-siswa', KategoriSiswaController::class);
        Route::resource('siswa', SiswaController::class);
        Route::resource('mentor', MentorController::class);
        Route::resource('class', KelasController::class);
        Route::get('/class/{kelasId}/assign', [KelasController::class, 'assign_kelas'])->name('assign_kelas');
        Route::post('/class/{kelasId}/assign', [KelasController::class, 'assign'])->name('assign');
        Route::resource('rapor', RaporController::class);
        Route::get('/cetak/{id}', [RaporController::class, 'cetak'])->name('cetak');
        
        Route::group(['prefix' => 'quiz'], function(){
            
            Route::resource('quiz-image', QuizImageController::class);
            Route::resource('quiz-sound', QuizSoundController::class);
            Route::resource('quiz-text', QuizTextController::class);
            Route::resource('quiz-video', QuizVideoController::class);
            
            Route::resource('question', QuestionController::class);
            Route::resource('exam', ExamController::class);
            Route::get('/exam/{examId}/assign', [ExamController::class, 'assign_exam'])->name('assign.exam');
            Route::post('/exam/{examId}/student', [ExamController::class, 'student'])->name('store_assign');
        });
    });
});
Route::get('/{path}', [HelperController::class, 'image'])->name('files.image');
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('files');

app/Models/Kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Kelas extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = ['id'];
    protected $fillable = [
        'user_id',
        'id_kategori_kelas',
        'title',
        'embed_video',
        'deksripsi',
        'image'
    ];
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function kategori_kelas()
    {
        return $this->belongsTo(KategoriKelas::class, 'id_kategori_kelas');
    }
    public function kelas_students(){
        return $this->hasMany(KelasStudent::class, 'kelas_id', 'id');
    }
    public function kelas_student(){
        return $this->hasOne(KelasStudent::class, 'kelas_id', 'id');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Kelas;
use App\Models\Mentor;
use App\Models\Siswa;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(Request $request)
    {
        $siswa = Siswa::with('user')->paginate(5);
        $siswaCount = User::where('role_id', 3)->where('status', 'Active')->count();
        $kelas = Kelas::all()->count();
        $mentor = Mentor::all()->count();
        return view('pages.dashboard.index', compact(['siswa', 'kelas', 'mentor', 'siswaCount']));
    }
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use App\Models\KategoriKelas;
use App\Models\Kelas;
use App\Models\KelasStudent;
use App\Models\Mentor;
use App\Models\Siswa;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();
        $keyword = $request->keyword;
        if(Auth::user()->role_id == 3){
            $kelas  = Kelas::with(['kategori_kelas', 'user'])->where('user_id', $user->id)
                ->whereHas('user', function ($query) use ($keyword) {
                    $query->where('name', 'LIKE', '%' . $keyword . '%');
                })->paginate(5);
                return view('pages.dashboard.kelas.index', compact('kelas'));
            }
            $kelas  = Kelas::with(['kategori_kelas', 'user'])->where('title', 'LIKE', '%' . $keyword . '%')->paginate(5);
            return view('pages.dashboard.kelas.index', compact('kelas'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $kategori = KategoriKelas::all();
        $kelas = Kelas::all();
        return view('pages.dashboard.kelas.create', compact(['kategori', 'kelas']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $user = Auth::user();
        $this->validate($request, [
            'title' => 'required',
            'embed_video' => 'required',
            'deskripsi' => 'required',
            'image' => 'required|image|mimes:png,jpg,jpeg'
        ]);
        $image  = $request->file('image');
        $image->storeAs('kelas-photo', $image->hashName());

        DB::beginTransaction();
        try {
            $kelas = new Kelas();
            $kelas->id_kategori_kelas = $request->id_kategori_kelas;
            $kelas->title = $request->title;
            $kelas->embed_video = $request->embed_video;
            $kelas->deskripsi = $request->deskripsi;
            $kelas->image = $image->hashName();
            $user->kelas()->save($kelas);
            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            return $e;
        }


        if ($kelas) {
            return redirect()->route('class.index')->with(['success' => 'Data berhasil disimpan!']);
        } else {
            return redirect()->route('class.index')->with(['error' => 'Data gagal disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kelas = Kelas::with(['kategori_kelas', 'user'])->findOrFail($id);
        return view('pages.dashboard.kelas.show', compact('kelas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kelas = Kelas::with(['kategori_kelas', 'user'])->findOrFail($id);
        $kategori_kelas = KategoriKelas::select('id', 'name')->get();
        return view('pages.dashboard.kelas.edit', compact(['kelas', 'kategori_kelas']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = Auth::user();
        $this->validate($request, [
            'title' => 'required',
            'embed_video' => 'required',
            'deskripsi' => 'required',
            'image' => 'required|image|mimes:png,jpg,jpeg'
        ]);

        $kelas =  Kelas::findOrFail($id);
        if ($request->file('photo') == "") {
            $kelas->id_kategori_kelas = $request->id_kategori_kelas;
            $kelas->title = $request->title;
            $kelas->embed_video = $request->embed_video;
            $kelas->deskripsi = $request->deskripsi;
            $user->kelas()->save($kelas);
        } else {
            Storage::disk('local')->delete('kelas-photo/' . $kelas->image);
            $image = $request->file('image');
            $image->storeAs('kelas-photo', $image->hashName());
            $kelas->image = $image->hashName();
            $kelas->id_kategori_kelas = $request->id_kategori_kelas;
            $kelas->title = $request->title;
            $kelas->embed_video = $request->embed_video;
            $kelas->deskripsi = $request->deskripsi;
            $user->kelas()->save($kelas);
        };
        return redirect()->route('class.index')->with(['success' => 'Data berhasil diubah !']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kelas = Kelas::findOrFail($id);
        $kelas->delete();
        return redirect()->route('class.index')->with(['success' => 'Data berhasil dihapus!']);
    }
    public function assign_kelas($kelasId){
        $kelas = Kelas::findOrFail($kelasId);
        $user_id = $kelas->user_id;
        $mentor_id = Mentor::where('user_id', $user_id)->first();
        $siswa = Siswa::where('mentor_id', $mentor_id->id)->whereHas('siswa_kelas', function($q) use($kelas){
            $q->where('kelas_id', $kelas->id);
            $q->where('siswa_id', '<>', 'siswa.id');
        })->get();
        $siswa = Siswa::where('mentor_id', $mentor_id->id)->whereNotIn('id', $siswa->modelKeys())->whereHas('user', function($query){
            $query->where('status', 'Active');
        })->get();
        return view('pages.dashboard.kelas.assign', compact(['kelas', 'siswa']));
    }

    public function assign(Request $request,$kelasId){
        $kelas = Kelas::findOrFail($kelasId);
        DB::beginTransaction();
        try{
            if((is_array($request->siswa_ids))){
                foreach($request->siswa_ids as $key => $siswaIds){
                    $kelasStudent = new KelasStudent();
                    $kelasStudent->kelas_id = $kelas->id;
                    $kelasStudent->siswa_id = $siswaIds;
                    $kelasStudent->save();
                }
            }
            DB::commit();
            return redirect()->route('class.index')->with(['success' => 'Data berhasil disimpan!']);
        }catch(Exception $e){
            DB::rollBack();
            return $e;
        }
    }
}

resources/views/pages/dashboard/kelas/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambah Kelas')

@section('content')
<div class="flex justify-between mt-10">
    <span class="self-center text-gray-600">
     Tambah Data Kelas | <a class="cursor-pointer" href="{{URL::previous()}}">Data Kelas </a> <span class="font-semibold"> - Tambah Kelas</span>
 </span> 
 <div class="col-span-3 mt-2 md:col-span-2">
     <a href="{{ route('class.index') }}"
         class="w-full px-3 py-2 border rounded-md shadow-sm cursor-pointer text-dark bg-slate-50 focus:outline-none hover:bg-slate-100"><i class="pr-3 fa-solid fa-arrow-left"></i>Kembali</a>
 </div>
 </div>
    <div class="min-h-screen">
        <div class="p-5 pb-20 mt-5 bg-white rounded shadow-sm ">
            <form action="{{ route('class.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase" for="kategori kelas">
                        Kategori Kelas
                    </label>
                    <div class="relative">
                        <select
                            class="block w-full px-4 py-3 pr-8 leading-tight text-gray-700 border border-gray-200 rounded appearance-none bg-zinc-50 focus:outline-none focus:bg-white focus:border-gray-500"
                            id="kelas_categories" name="id_kategori_kelas" required>
                            <option selected=true disabled="disabled">Pilih Kategori</option>
                            @foreach ($kategori as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase" for="image">
                        Thumbnail Kelas</label>
                    <input
                        class="block w-full mb-5 text-xs text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-zinc-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                        id="image" type="file" name="image">
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Judul Kelas</label>
                    <input type="text" name="title" value="{{ old('title') }}"
                        class="w-full p-2 mt-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                        placeholder="Cth: Kelas Writing" required>
                    @error('title')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Embed Video</label>
                    <div class="flex">
                        <span class="inline-flex items-center p-2 px-3 text-sm text-gray-900 bg-gray-100 border border-r-0 border-gray-300 rounded-l-md ">
                            Youtube.com/
                          </span>
                          <input type="text" name="embed_video" value="{{ old('embed_video') }}"
                              class="w-full p-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                              placeholder="....." required>
                    </div>
                    @error('embed_video')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Deskripsi
                        Kelas</label>
                    <textarea id="message" rows="4" name='deskripsi' value="{{ old('deskripsi') }}"
                        class="block p-2.5 w-full text-sm focus:border-gray-500 text-gray-900 bg-zinc-50 rounded-lg border border-gray-300"
                        placeholder="Deskripsi kelas ..." required>{{ old('deskripsi') }}</textarea>
                    @error('deskripsi')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mt-5">
                    <button type="submit"
                        class="p-2 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">SIMPAN
                        KELAS</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/dashboard/kelas/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Edit Kelas')

@section('content')
<div class="flex justify-between mt-10">
    <span class="self-center text-gray-600">
     Edit Data Kelas | <a class="cursor-pointer" href="{{URL::previous()}}">Data Kelas </a> <span class="font-semibold"> - Edit Kelas</span>
 </span> 
 <div class="col-span-3 mt-2 md:col-span-2">
     <a href="{{ route('class.index') }}"
         class="w-full px-3 py-2 border rounded-md shadow-sm cursor-pointer text-dark bg-slate-50 focus:outline-none hover:bg-slate-100"><i class="pr-3 fa-solid fa-arrow-left"></i>Kembali</a>
 </div>
 </div>
    <div class="min-h-screen">
        <div class="p-5 pb-20 mt-5 bg-white rounded shadow-sm ">
            <form action="{{ route('class.update', $kelas->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase" for="kategori kelas">
                        Kategori Kelas
                    </label>
                    <div class="relative">
                        <select
                            class="block w-full px-4 py-3 pr-8 leading-tight text-gray-700 border border-gray-200 rounded appearance-none bg-zinc-50 focus:outline-none focus:bg-white focus:border-gray-500"
                            id="kelas_categories" name="id_kategori_kelas" required>
                            <option selected=true disabled="disabled">Pilih Kategori</option>
                            @foreach ($kategori_kelas as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase" for="image">
                        Thumbnail Kelas</label>
                    <input
                        class="block w-full mb-5 text-xs text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-zinc-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                        id="image" type="file" name="image">
                        @if ($kelas->image)
                         <img width="200px"src="{{asset('storage/kelas-photo/'. $kelas->image)}}" alt="">
                        @endif
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Judul Kelas</label>
                    <input type="text" name="title" value="{{ old('title', $kelas->title) }}"
                        class="w-full p-2 mt-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                        placeholder="Cth: Kelas Writing" required>
                    @error('title')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Embed Video</label>
                    <input type="text" name="embed_video" value="{{ old('embed_video', $kelas->embed_video) }}"
                        class="w-full p-2 mt-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                        placeholder="Cth: Youtube.com/" required>
                    @error('title')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mt-5">
                    <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">Deskripsi
                        Kelas</label>
                    <textarea id="message" rows="4" name='deskripsi' value="{{ old('deskripsi') }}"
                        class="block p-2.5 w-full text-sm focus:border-gray-500 text-gray-900 bg-zinc-50 rounded-lg border border-gray-300"
                        placeholder="Deskripsi kelas ..." required>{{ old('deskripsi', $kelas->deskripsi) }}</textarea>
                    @error('deskripsi')
                        <div class="p-2 mt-2 bg-red-400 rounded shadow-sm">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="mt-5">
                    <button type="submit"
                        class="p-2 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">UPDATE
                        KELAS</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/dashboard/kelas/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Kelas')

@section('content')

    <div class="p-5 mt-20 bg-white rounded shadow-sm">
        <div class="flex justify-between py-2 mb-3">
            <div >
                <p class="text-base font-semibold ">
                    Data Kelas
                </p>
                <p class="text-sm text-slate-500">Daftar kelas <span class="text-primary"> Naladhipa Courses</span></p>
            </div>
            @if (Auth::user()->role_id == 3)     
            <div class="col-span-3 mt-2 md:col-span-2">
                <a href="{{ route('class.create') }}"
                    class="w-full p-3 text-white uppercase bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">TAMBAH
                    Kelas</a>
            </div>
            @endif
        </div>
        <div class="grid grid-cols-6 mb-4 md:grid-cols-8 md:gap-4 ">
            <div class="col-span-3 md:col-span-3">
                <form action="{{ route('class.index') }}" method="GET">
                    <input type="text" name="keyword"
                        class="w-full p-2 border border-gray-200 rounded shadow-sm bg-zinc-50 focus:outline-none focus:bg-white"
                        placeholder="Search...">
                </form>
            </div>
        </div>

        <div class="md:relative sm:rounded-lg">
            <div class="flex items-center justify-between pb-4">

            </div>
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr class="items-center">
                        <th scope="col" class="px-6 py-3 ">
                            No
                        </th>
                        <th scope="col" class="px-6 py-3 ">
                            Judul Kelas
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Author
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Aksi
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @forelse ($kelas as $key => $item)
                        <tr
                            class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <td class="px-6 py-4">
                                <div class="pl-3">
                                    <p class="text-base font-semibold">{{ $key + 1 }}</p>
                                </div>
                            </td>
                            <td class="px-6 py-4">
                                <p class="text-base font-medium">{{ $item->title }}</p>
                            </td>
                            <td class="px-6 py-4">
                                <p class="text-base font-medium">{{ $item->user->name }}</p>
                            </td>
                            <td class="inline-flex items-center self-center px-6 py-4 ">
                                @if (Auth::user()->role_id == 1)   
                                <a href="{{route('assign', $item->id)}}" type="button" class="self-center text-white bg-gray-400 hover:bg-gray-600 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center">Tambah Siswa</a>
                                @endif
                                @if (Auth::user()->role_id == 3)       
                                <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown-{{$item}}"
                                    class="self-center text-white bg-gray-400 hover:bg-gray-600 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center"
                                    type="button">Aksi <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none"
                                        stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M19 9l-7 7-7-7"></path>
                                    </svg></button>
                                @endif
                                <!-- Dropdown menu -->
                                <div id="dropdown-{{$item}}"
                                    class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                                    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200"
                                        aria-labelledby="dropdownDefaultButton">
                                        <li>
                                            <a href="{{route('class.show', $item->id)}}" class="block px-4 py-2 hover:bg-gray-100 ">Detail</a>
                                        </li>
                                        @if (Auth::user()->role_id == 1)     
                                        <li>
                                            <a href="{{route('assign_kelas', $item->id)}}" class="block px-4 py-2 hover:bg-gray-100 ">Assign Kelas</a>
                                        </li>
                                        @endif
                                        <li>
                                            <a href="{{ route('class.edit', $item->id) }}" class="block px-4 py-2 ">Edit</a>
                                        </li>
                                        <li>
                                            <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                                action="{{ route('class.destroy', $item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit"
                                                    class="w-full px-4 py-2 text-left delete-confirm hover:bg-gray-100 focus:outline-none">
                                                    Delete</button>
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <div class="p-3 mb-3 text-white bg-red-500 rounded shadow-sm">
                            Data Belum Tersedia!
                        </div>
                    @endforelse

                </tbody>
            </table>
            <div class="mt-2">
                {{ $kelas->withQueryString()->links('vendor.pagination.tailwind') }}
            </div>
        </div>
    </div>
    <script>
        $('.delete-confirm').on('click', function (event) {
           event.preventDefault();
           const url = $(this).attr('href');
           swal({
               title: 'Are you sure?',
               text: 'This record and it`s details will be permanantly deleted!',
               icon: 'warning',
               buttons: ["Cancel", "Yes!"],
               }).then(function(value) {
               if (value) {
               window.location.href = url;
             }
           });
          });
     </script>
@endsection