routes/web.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KategoriSiswaController;
use App\Http\Controllers\Landing\HalamanKelasController;
use App\Http\Controllers\Landing\ProfileController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
Route::get('/edit', [ProfileController::class, 'edit'])->name('edit.profile');
Route::put('/update', [ProfileController::class, 'update'])->name('update.profile');
Route::get('/header', [ProfileController::class, 'header'])->name('header');
Route::get('/cetak/{raporId}', [ProfileController::class, 'cetak'])->name('print');
Route::get('/cetak-siswa', [ProfileController::class, 'cetakSiswa'])->name('siswa-print');
// Authentication
Route::get('login', [AuthController::class, 'login'])->name('login');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'registerUser'])->name('registerUser');
Route::post('login', [AuthController::class, 'authenticate']);
Route::post('logout', [AuthController::class, 'logout'])->name('logout');

// Route::middleware(['auth'], function(){
    Route::post('/reset-password', [ProfileController::class, 'resetPassword'])->name('reset-password');
    // });
    // route::get('kelas', [HalamanKelasController::class, 'getKelas'])->name('kelas');
    
    Route::group(['prefix' => 'kelas', 'middleware' => ['auth']], function () {
        Route::get('/', [HalamanKelasController::class, 'index'])->name('list.kelas');
        Route::get('/{kelasId}', [HalamanKelasController::class, 'show'])->name('detail.kelas');
        Route::put('/{kelasId}', [HalamanKelasController::class, 'changeStatus'])->name('changeStatus');
});

Route::group(['prefix' => 'exam', 'middleware' => ['auth']], function(){
    Route::get('/', [HalamanQuizController::class, 'index'])->name('list.exam');
    Route::get('/{examId}', [HalamanQuizController::class, 'show'])->name('detail.exam');
    Route::post('/{examId}', [HalamanQuizController::class, 'test'])->name('test');
});
Route::group([
    'middleware' => ['auth']
], function () {
    Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Admin,Mentor']], function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::resource('role', RoleController::class);
        Route::resource('user', UserController::class);
        Route::get('/user/{id}/{status}', [UserController::class, 'changeStatus'])->name('change-status');
        Route::post('/user/{id}/reset', [UserController::class, 'reset'])->name('reset');
        Route::resource('kategori-siswa', KategoriSiswaController::class);
        Route::resource('siswa', SiswaController::class);
        Route::resource('mentor', MentorController::class);
        Route::resource('class', KelasController::class);
        Route::get('/class/{kelasId}/assign', [KelasController::class, 'assign_kelas'])->name('assign_kelas');
        Route::post('/class/{kelasId}/assign', [KelasController::class, 'assign'])->name('assign');
        Route::resource('rapor', RaporController::class);
        Route::get('/cetak/{id}', [RaporController::class, 'cetak'])->name('cetak');
        
        Route::group(['prefix' => 'quiz'], function(){
            
            Route::resource('quiz-image', QuizImageController::class);
            Route::resource('quiz-sound', QuizSoundController::class);
            Route::resource('quiz-text', QuizTextController::class);
            Route::resource('quiz-video', QuizVideoController::class);
            
            Route::resource('question', QuestionController::class);
            Route::resource('exam', ExamController::class);
            Route::get('/exam/{examId}/assign', [ExamController::class, 'assign_exam'])->name('assign.exam');
            Route::post('/exam/{examId}/student', [ExamController::class, 'student'])->name('store_assign');
        });
    });
});
Route::get('/{path}', [HelperController::class, 'image'])->name('files.image');
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('files');

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Siswa extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'siswa';

    protected $fillable = [
        'mentor_id',
        'user_id',
        'alamat',
        'no_hp',
        'photo',
        'kelas'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function kategori_siswa()
    {
        return $this->belongsTo(KategoriSiswa::class, 'id_siswa_categories');
    }

    public function rapor()
    {
        return $this->hasMany(Rapor::class, 'siswa_id', 'id');
    }
    public function siswa_kelas(){
        return $this->hasMany(KelasStudent::class, 'siswa_id', 'id');
    }
    public function exam_students(){
        return $this->hasMany(ExamStudent::class,'siswa_id', 'id');
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\KategoriSiswa;
use App\Models\Mentor;
use App\Models\Siswa;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keyword = $request->keyword;
        $siswa = Siswa::with(['kategori_siswa', 'user'])
            ->whereHas('user', function ($query) use ($keyword) {
                $query->where('name', 'LIKE', '%' . $keyword . '%');
            })->paginate(5);

        // dd($siswa);
        return view('pages.dashboard.siswa.index', compact('siswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()

    {
        $siswa = Siswa::all();
        // $user = User::where('id_role', '3')->get();      

        $user = User::where('role_id', '2')
            ->whereHas('siswa', function ($q) {
                $q->where('user_id', '<>', 'user.id');
            })->get();

        $user = User::whereNotIn('id', $user->modelKeys())
            ->where('role_id', '2')->get();

        $mentor = Mentor::all();


        return view('pages.dashboard.siswa.create', compact([ 'user', 'siswa', 'mentor']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [


            'alamat' => 'required|max:255',
            'photo' => 'required|image|mimes:png,jpg,jpeg',
            'no_hp' => 'required|numeric|min:11',
            'kelas' => 'required'
        ]);

        $photo  = $request->file('photo');
        $photo->storeAs('siswa-photo', $photo->hashName());
        $siswa =  Siswa::firstOrCreate(
            [
                'user_id' => $request->user_id,
            ],
            [
                'user_id' => $request->user_id,
                'mentor_id' => $request->mentor_id,
                'alamat' => $request->alamat,
                'photo' => $photo->hashName(),
                'no_hp' => $request->no_hp,
                'kelas' => $request->kelas
            ]
        );

        if ($siswa) {

            return redirect()->route('siswa.index')->with(['success' => 'Data berhasil disimpan!']);
        } else {
            return redirect()->route('siswa.index')->with(['error' => 'Data gagal disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $siswa = Siswa::findOrFail($id);
        $kategori_siswa = KategoriSiswa::select('id', 'name')->get();
        $mentor = Mentor::all();
        $user = User::where('role_id', 2)->get();
        // dd($user->modelKeys());

        return view('pages.dashboard.siswa.edit', compact(['siswa', 'kategori_siswa', 'user','mentor']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [

            'alamat' => 'required|max:255',
            'photo' => 'nullable|image|mimes:png,jpg,jpeg',
            'no_hp' => 'required',
            'kelas' => 'required'
        ]);
        $siswa = Siswa::findOrFail($id);
        if ($request->file('photo') == "") {
            $siswa->alamat = $request->alamat;
            $siswa->mentor_id = $request->mentor_id;
            $siswa->no_hp = $request->no_hp;
            $siswa->kelas = $request->kelas;
            $siswa->save();
        } else {
            Storage::disk('local')->delete('siswa-photo/' . $siswa->photo);
            $photo  = $request->file('photo');
            $photo->storeAs('siswa-photo', $photo->hashName());
            $siswa->photo = $photo->hashName();
            $siswa->mentor_id = $request->mentor_id;
            $siswa->alamat = $request->alamat;
            $siswa->no_hp = $request->no_hp;
            $siswa->kelas = $request->kelas;
            $siswa->save();
        }

        return redirect()->route('siswa.index')->with(['success' => 'Data berhasil diubah!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $siswa = Siswa::findOrFail($id);
        $siswa->delete();
        return redirect()->route('siswa.index')->with(['success' => 'Data berhasil dihapus!']);
    }
}

resources/views/pages/dashboard/siswa/kategori/create.blade.php
@extends('layouts.dashboard', ['title' => 'Tambah Kategori'])

@section('content')
    <div class="p-5 bg-white rounded shadow-sm mt-36">
        <form action="{{ route('kategoriSiswa.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="mt-5">
                <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase ">NAMA KATEGORI
                    SISWA</label>
                <input type="text" name="name" value="{{ old('name') }}"
                    class="w-full p-2 mt-2 bg-gray-200 border border-gray-200 rounded shadow-sm focus:outline-none focus:bg-white"
                    placeholder="Nama Kategori Siswa">

            </div>
            <div class="mt-5">
                <button type="submit"
                    class="p-2 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">SIMPAN
                    KATEGORI SISWA</button>
            </div>

        </form>
    </div>
@endsection

resources/views/pages/dashboard/siswa/kategori/edit.blade.php
@extends('layouts.dashboard')
@section('title', 'Edit Role')

@section('content')
    <div class="p-5 mt-20 bg-white rounded shadow-sm">
        <form action="{{ route('kategori-siswa.update', $siswaCategories) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="mt-5">
                <label>Nama Role</label>
                <input type="text" name="name" value="{{ old('role', $siswaCategories->name) }}"
                    class="w-full p-2 mt-2 bg-gray-200 border border-gray-200 rounded shadow-sm focus:outline-none focus:bg-white"
                    placeholder="Nama Role">
            </div>
            <div class="mt-5">
                <button type="submit"
                    class="p-2 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">UPDATE
                    KATEGORI SISWA</button>
            </div>

        </form>
    </div>
@endsection

resources/views/pages/dashboard/siswa/kategori/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Kategori Siswa')

@section('content')

    <div class="p-5 bg-white rounded shadow-sm mt-28">
        <div class="grid grid-cols-6 mb-4 md:grid-cols-8 md:gap-4 ">
            <div class="col-span-3 mt-2 md:col-span-2">
                <a href="{{ route('kategori-siswa.create') }}"
                    class="w-full p-3 text-white bg-indigo-500 rounded shadow-sm focus:outline-none hover:bg-indigo-700">TAMBAH
                    KATEGORI SISWA</a>
            </div>
            <div class="col-span-3 md:col-span-6">
                <form action="{{ route('kategori-siswa.index') }}" method="GET">
                    <input type="text" name="search"
                        class="w-full p-2 bg-gray-200 border border-gray-200 rounded shadow-sm focus:outline-none focus:bg-white"
                        placeholder="ketik judul kategori dan enter">
                </form>
            </div>
        </div>

        <div class="overflow-x-auto md:relative sm:rounded-lg">
            <div class="flex items-center justify-between pb-4">

            </div>
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr class="items-center">
                        <th scope="col" class="px-6 py-3 ">
                            No
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Kategori Siswa
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Aksi
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @forelse ($siswaCategories as $key => $item)
                        <tr
                            class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <th scope="row" class="flex items-center px-6 py-4 text-gray-900">
                                <div class="pl-3">
                                    <p class="text-base font-semibold">{{ $key + 1 }}</p>
                                </div>
                            </th>
                            <td class="px-6 py-4">
                                <p class="text-base font-medium">{{ $item->name }}</p>
                            </td>
                            <td class="inline-flex px-6 py-4 text-center ">
                                <button
                                    class="px-4 py-2 mr-2 text-xs text-white rounded bg-emerald-500 hover:border-indigo-700 focus:outline-none"><a
                                        href="{{ route('kategori-siswa.edit', $item) }}">EDIT</a></button>
                                <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                    action="{{ route('kategori-siswa.destroy', $item) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit"
                                        class="px-4 py-2 text-xs text-white bg-red-500 rounded hover:border-red-700 focus:outline-none">
                                        HAPUS</button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <div class="p-3 mb-3 text-white bg-red-500 rounded shadow-sm">
                            Data Belum Tersedia!
                        </div>
                    @endforelse

                </tbody>
            </table>
        </div>
    @endsection